- import_playbook: setup.yml
- import_playbook: install-act.yml
- import_playbook: install-gnu-radio.yml
- import_playbook: install-miniconda.yml
- import_playbook: install-network-tools.yml
- import_playbook: install-ocr-tools.yml
- import_playbook: install-wxsat-tools.yml
- import_playbook: increase-swap-size.yml
- import_playbook: setup-ai-laptop.yml
- import_playbook: install-vscode.yml
- import_playbook: install-syncthing.yml
